FROM jenkins/jenkins:lts

USER root

# Instalar paquetes necesarios
RUN apt-get update && \
    apt-get install -y \
        curl \
        gnupg \
        lsb-release \
        software-properties-common \
        maven \
        docker.io && \
    apt-get clean

# Dar permisos de docker al usuario jenkins
RUN usermod -aG docker jenkins

USER jenkins