services:

  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: always
    environment:
      MYSQL_DATABASE: db_sysalud
      MYSQL_USER: root
      MYSQL_PASSWORD: giangodisinyou2
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3307:3306"
    networks:
      - jenkins_net

  sonarqube:
    image: sonarqube:latest
    container_name: sonarqube
    ports:
      - "9000:9000"
    environment:
      - SONAR_JDBC_URL=jdbc:postgresql://sonar-db:5432/sonar
      - SONAR_JDBC_USERNAME=sonar
      - SONAR_JDBC_PASSWORD=sonar
    depends_on:
      - sonar-db
    networks:
      - jenkins_net

  sonar-db:
    image: postgres:14
    container_name: sonar-db
    restart: always
    environment:
      POSTGRES_USER: sonar
      POSTGRES_PASSWORD: sonar
      POSTGRES_DB: sonar
    volumes:
      - sonar_db_data:/var/lib/postgresql/data
    networks:
      - jenkins_net

volumes:
  sonar_db_data:

networks:
  jenkins_net:
    driver: bridge
