version: '3.8'

services:
  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    user: root  # necesario para poder usar docker.sock
    ports:
      - "8080:8080"   # Jenkins UI
      - "50000:50000" # Jenkins agents
    volumes:
      - ./jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - jenkins_net

  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: always
    environment:
      MYSQL_DATABASE: db_sysalud
      MYSQL_USER: root
      MYSQL_PASSWORD: giangodisinyou2
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    networks:
      - jenkins_net

networks:
  jenkins_net:
    driver: bridge