global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'spring'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['app:8081']  # "app" es el nombre del servicio en docker-compose